apiVersion: apps/v1
kind: Deployment
metadata:
  name: guess-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guess
  template:
    metadata:
      labels:
        app: guess
    spec:
      containers:
      - name: guess
        image: us-central1-docker.pkg.dev/supple-serenity-458404-e9/gae-standard/app/default:0e5c5a19-942c-40ef-9191-5b7d2a2ba9d3
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        command: ["/hello-app"]
        args: ["-crash"]
